// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tltermgwswifpklpvcgq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRsdGVybWd3c3dpZnBrbHB2Y2dxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMjQ5NTMsImV4cCI6MjA2NTYwMDk1M30.EtDHvDbGG41BiwWPZ1npTpjweGudAxT-pGZnqgxDwu8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);